name: Pruebas Unitarias Java

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Comprobar el código fuente
              uses: actions/checkout@v2

            - name: Configurar JDK 11
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Ejecutar pruebas unitarias
              run: mvn test
